timeout: 3
verbose: yes
/Os
    protocol: limine
    kernel_path: boot():/kernel.elf
    module_path: boot():/init.img
    paging_mode: 4level
    max_paging_mode: 4level
    randomise_hhdm_base: yes
    resolution: 1920x1080x32